col_list = [
    'symbol', 
    'zip', 
    'sector', 
    'fullTimeEmployees', 
    'longBusinessSummary', 
    'city', 
    'phone', 
    'state', 
    'country', 
    'companyOfficers', 
    'website', 
    'maxAge', 
    'address1', 
    'fax', 
    'industry', 
    'address2', 
    'ebitdaMargins', 
    'profitMargins', 
    'grossMargins', 
    'operatingCashflow', 
    'revenueGrowth', 
    'operatingMargins', 
    'ebitda', 
    'targetLowPrice', 
    'recommendationKey', 
    'grossProfits', 
    'freeCashflow', 
    'targetMedianPrice', 
    'currentPrice', 
    'earningsGrowth', 
    'currentRatio', 
    'returnOnAssets', 
    'numberOfAnalystOpinions', 
    'targetMeanPrice', 
    'debtToEquity', 
    'returnOnEquity', 
    'targetHighPrice', 
    'totalCash', 
    'totalDebt', 
    'totalRevenue', 
    'totalCashPerShare', 
    'financialCurrency', 
    'revenuePerShare', 
    'quickRatio', 
    'recommendationMean', 
    'exchange', 
    'shortName', 
    'longName', 
    'exchangeTimezoneName', 
    'exchangeTimezoneShortName', 
    'isEsgPopulated', 
    'gmtOffSetMilliseconds', 
    'underlyingSymbol', 
    'quoteType', 
    'underlyingExchangeSymbol', 
    'headSymbol', 
    'messageBoardId', 
    'uuid', 
    'market', 
    'annualHoldingsTurnover', 
    'enterpriseToRevenue', 
    'beta3Year', 
    'enterpriseToEbitda', 
    '52WeekChange', 
    'morningStarRiskRating', 
    'forwardEps', 
    'revenueQuarterlyGrowth', 
    'sharesOutstanding', 
    'fundInceptionDate', 
    'annualReportExpenseRatio', 
    'totalAssets', 
    'bookValue', 
    'sharesShort', 
    'sharesPercentSharesOut', 
    'fundFamily', 
    'lastFiscalYearEnd', 
    'heldPercentInstitutions', 
    'netIncomeToCommon', 
    'trailingEps', 
    'lastDividendValue', 
    'SandP52WeekChange', 
    'priceToBook', 
    'heldPercentInsiders', 
    'nextFiscalYearEnd', 
    'yield', 
    'mostRecentQuarter', 
    'shortRatio', 
    'sharesShortPreviousMonthDate', 
    'floatShares', 
    'beta', 
    'enterpriseValue', 
    'priceHint', 
    'threeYearAverageReturn', 
    'lastSplitDate', 
    'lastSplitFactor', 
    'legalType',
    'morningStarOverallRating', 
    'earningsQuarterlyGrowth', 
    'priceToSalesTrailing12Months', 
    'dateShortInterest', 
    'pegRatio', 
    'ytdReturn', 
    'forwardPE', 
    'lastCapGain', 
    'shortPercentOfFloat',
    'sharesShortPriorMonth', 
    'category', 
    'fiveYearAverageReturn', 
    'previousClose', 
    'regularMarketOpen', 
    'twoHundredDayAverage', 
    'trailingAnnualDividendYield', 
    'payoutRatio', 
    'volume24Hr', 
    'regularMarketDayHigh', 
    'navPrice', 
    'averageDailyVolume10Day', 
    'regularMarketPreviousClose', 
    'fiftyDayAverage', 
    'trailingAnnualDividendRate', 
    'open', 
    'averageVolume10days', 
    'expireDate', 
    'algorithm', 
    'dividendRate', 
    'exDividendDate', 
    'circulatingSupply', 
    'startDate', 
    'regularMarketDayLow', 
    'currency', 
    'trailingPE', 
    'regularMarketVolume', 
    'lastMarket', 
    'maxSupply', 
    'openInterest', 
    'marketCap', 
    'volumeAllCurrencies', 
    'strikePrice', 
    'averageVolume', 
    'dayLow', 
    'ask', 
    'askSize', 
    'volume', 
    'fiftyTwoWeekHigh', 
    'fromCurrency', 
    'fiveYearAvgDividendYield', 
    'fiftyTwoWeekLow', 
    'bid', 
    'tradeable', 
    'dividendYield', 
    'bidSize', 
    'dayHigh', 
    'regularMarketPrice', 
    'logo_url',
    'quoteSourceName', 
    'averageDailyVolume3Month', 
    'regularMarketTime', 
    'regularMarketChange', 
    'preMarketPrice', 
    'exchangeDataDelayedBy', 
    'postMarketChange', 
    'postMarketPrice', 
    'exchangeName', 
    'preMarketChange', 
    'regularMarketSource', 
    'marketState',
    ]    

scan_col_list = [
    'symbol', 
    'sector', 
    'industry', 
    # 'ebitdaMargins', 
    # 'profitMargins', 
    # 'grossMargins', 
    # 'operatingCashflow', 
    # 'revenueGrowth', 
    # 'operatingMargins', 
    # 'ebitda', 
    # 'targetLowPrice', 
    # 'recommendationKey', 
    # 'grossProfits', 
    # 'freeCashflow', 
    # 'targetMedianPrice', 
    # 'currentPrice', 
    # 'earningsGrowth', 
    # 'currentRatio', 
    # 'returnOnAssets', 
    # 'numberOfAnalystOpinions', 
    # 'targetMeanPrice', 
    # 'debtToEquity', 
    # 'returnOnEquity', 
    # 'targetHighPrice', 
    # 'totalCash', 
    # 'totalDebt', 
    # 'totalRevenue', 
    # 'totalCashPerShare', 
    # 'financialCurrency', 
    # 'revenuePerShare', 
    # 'quickRatio', 
    # 'recommendationMean', 
    # 'shortName', 
    # 'longName', 
    # 'isEsgPopulated', 
    # 'market', 
    # 'annualHoldingsTurnover', 
    # 'enterpriseToRevenue', 
    # 'beta3Year', 
    # 'enterpriseToEbitda', 
    # '52WeekChange', 
    # 'morningStarRiskRating', 
    # 'forwardEps', 
    # 'revenueQuarterlyGrowth', 
    # 'sharesOutstanding', 
    # 'annualReportExpenseRatio', 
    # 'totalAssets', 
    # 'bookValue', 
    # 'sharesShort', 
    # 'sharesPercentSharesOut', 
    # 'fundFamily', 
    # 'heldPercentInstitutions', 
    # 'netIncomeToCommon', 
    # 'trailingEps', 
    # 'lastDividendValue', 
    # 'SandP52WeekChange', 
    # 'priceToBook', 
    # 'heldPercentInsiders', 
    # 'yield', 
    # 'shortRatio', 
    # 'sharesShortPreviousMonthDate', 
    # 'floatShares', 
    # 'beta', 
    # 'enterpriseValue', 
    # 'priceHint', 
    # 'threeYearAverageReturn', 
    # 'lastSplitDate', 
    # 'lastSplitFactor', 
    # 'legalType',
    # 'morningStarOverallRating', 
    # 'earningsQuarterlyGrowth', 
    # 'priceToSalesTrailing12Months', 
    # 'dateShortInterest', 
    # 'pegRatio', 
    # 'ytdReturn', 
    # 'forwardPE', 
    # 'lastCapGain', 
    # 'shortPercentOfFloat',
    # 'sharesShortPriorMonth', 
    # 'category', 
    # 'fiveYearAverageReturn', 
    # 'previousClose', 
    # 'regularMarketOpen', 
    # 'twoHundredDayAverage', 
    # 'trailingAnnualDividendYield', 
    # 'payoutRatio', 
    # 'volume24Hr', 
    # 'regularMarketDayHigh', 
    # 'navPrice', 
    # 'averageDailyVolume10Day', 
    # 'regularMarketPreviousClose', 
    # 'fiftyDayAverage', 
    # 'trailingAnnualDividendRate', 
    # 'open', 
    # 'averageVolume10days', 
    # 'expireDate', 
    # 'algorithm', 
    # 'dividendRate', 
    # 'exDividendDate', 
    # 'circulatingSupply', 
    # 'startDate', 
    # 'regularMarketDayLow', 
    # 'trailingPE', 
    # 'regularMarketVolume', 
    # 'lastMarket', 
    # 'maxSupply', 
    # 'openInterest', 
    # 'marketCap', 
    # 'volumeAllCurrencies', 
    # 'strikePrice', 
    # 'averageVolume', 
    # 'dayLow', 
    # 'ask', 
    # 'askSize', 
    # 'volume', 
    # 'fiftyTwoWeekHigh', 
    # 'fromCurrency', 
    # 'fiveYearAvgDividendYield', 
    # 'fiftyTwoWeekLow', 
    # 'bid', 
    'tradeable', 
    # 'dividendYield', 
    # 'bidSize', 
    # 'dayHigh', 
    # 'regularMarketPrice', 
    # 'quoteSourceName', 
    # 'averageDailyVolume3Month', 
    # 'regularMarketTime', 
    # 'regularMarketChange', 
    # 'preMarketPrice', 
    # 'exchangeDataDelayedBy', 
    # 'postMarketChange', 
    # 'postMarketPrice', 
    # 'exchangeName', 
    # 'preMarketChange', 
    # 'regularMarketSource', 
    # 'marketState',

]
scan_col_list_2 = [
    'symbol', 
    # 'zip', 
    'sector', 
    # 'fullTimeEmployees', 
    # 'longBusinessSummary', 
    # 'city', 
    # 'phone', 
    # 'state', 
    # 'country', 
    # 'companyOfficers', 
    # 'website', 
    # 'maxAge', 
    # 'address1', 
    # 'fax', 
    'industry', 
    # 'address2', 
    'ebitdaMargins', 
    'profitMargins', 
    'grossMargins', 
    'operatingCashflow', 
    'revenueGrowth', 
    'operatingMargins', 
    'ebitda', 
    'targetLowPrice', 
    'recommendationKey', 
    'grossProfits', 
    'freeCashflow', 
    'targetMedianPrice', 
    'currentPrice', 
    'earningsGrowth', 
    'currentRatio', 
    'returnOnAssets', 
    'numberOfAnalystOpinions', 
    'targetMeanPrice', 
    'debtToEquity', 
    'returnOnEquity', 
    'targetHighPrice', 
    'totalCash', 
    'totalDebt', 
    'totalRevenue', 
    'totalCashPerShare', 
    'financialCurrency', 
    'revenuePerShare', 
    'quickRatio', 
    'recommendationMean', 
    # 'exchange', 
    'shortName', 
    'longName', 
    # 'exchangeTimezoneName', 
    # 'exchangeTimezoneShortName', 
    'isEsgPopulated', 
    # 'gmtOffSetMilliseconds', 
    # 'underlyingSymbol', 
    # 'quoteType', 
    # 'underlyingExchangeSymbol', 
    # 'headSymbol', 
    # 'messageBoardId', 
    # 'uuid', 
    'market', 
    'annualHoldingsTurnover', 
    'enterpriseToRevenue', 
    'beta3Year', 
    'enterpriseToEbitda', 
    '52WeekChange', 
    'morningStarRiskRating', 
    'forwardEps', 
    'revenueQuarterlyGrowth', 
    'sharesOutstanding', 
    # 'fundInceptionDate', 
    'annualReportExpenseRatio', 
    'totalAssets', 
    'bookValue', 
    'sharesShort', 
    'sharesPercentSharesOut', 
    'fundFamily', 
    # 'lastFiscalYearEnd', 
    'heldPercentInstitutions', 
    'netIncomeToCommon', 
    'trailingEps', 
    'lastDividendValue', 
    'SandP52WeekChange', 
    'priceToBook', 
    'heldPercentInsiders', 
    # 'nextFiscalYearEnd', 
    'yield', 
    # 'mostRecentQuarter', 
    'shortRatio', 
    'sharesShortPreviousMonthDate', 
    'floatShares', 
    'beta', 
    'enterpriseValue', 
    'priceHint', 
    'threeYearAverageReturn', 
    'lastSplitDate', 
    'lastSplitFactor', 
    'legalType',
    'morningStarOverallRating', 
    'earningsQuarterlyGrowth', 
    'priceToSalesTrailing12Months', 
    'dateShortInterest', 
    'pegRatio', 
    'ytdReturn', 
    'forwardPE', 
    'lastCapGain', 
    'shortPercentOfFloat',
    'sharesShortPriorMonth', 
    'category', 
    'fiveYearAverageReturn', 
    'previousClose', 
    'regularMarketOpen', 
    'twoHundredDayAverage', 
    'trailingAnnualDividendYield', 
    'payoutRatio', 
    'volume24Hr', 
    'regularMarketDayHigh', 
    'navPrice', 
    'averageDailyVolume10Day', 
    'regularMarketPreviousClose', 
    'fiftyDayAverage', 
    'trailingAnnualDividendRate', 
    'open', 
    'averageVolume10days', 
    'expireDate', 
    'algorithm', 
    'dividendRate', 
    'exDividendDate', 
    'circulatingSupply', 
    'startDate', 
    'regularMarketDayLow', 
    # 'currency', 
    'trailingPE', 
    'regularMarketVolume', 
    'lastMarket', 
    'maxSupply', 
    'openInterest', 
    'marketCap', 
    'volumeAllCurrencies', 
    'strikePrice', 
    'averageVolume', 
    'dayLow', 
    'ask', 
    'askSize', 
    'volume', 
    'fiftyTwoWeekHigh', 
    'fromCurrency', 
    'fiveYearAvgDividendYield', 
    'fiftyTwoWeekLow', 
    'bid', 
    'tradeable', 
    'dividendYield', 
    'bidSize', 
    'dayHigh', 
    'regularMarketPrice', 
    # 'logo_url',
    'quoteSourceName', 
    'averageDailyVolume3Month', 
    'regularMarketTime', 
    'regularMarketChange', 
    'preMarketPrice', 
    'exchangeDataDelayedBy', 
    'postMarketChange', 
    'postMarketPrice', 
    'exchangeName', 
    'preMarketChange', 
    'regularMarketSource', 
    'marketState',
    ]    
